# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='can.proto',
  package='CANProto',
  serialized_pb=_b('\n\tcan.proto\x12\x08\x43\x41NProto\"-\n\x08VehSpeed\x12\r\n\x05speed\x18\x01 \x02(\x02\x12\x12\n\ntime_stamp\x18\x02 \x02(\x03\"/\n\nWheelAngle\x12\r\n\x05\x61ngle\x18\x01 \x02(\x02\x12\x12\n\ntime_stamp\x18\x02 \x02(\x03\"(\n\x04Gear\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x12\n\ntime_stamp\x18\x02 \x02(\x03\".\n\nTurnSignal\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x12\n\ntime_stamp\x18\x02 \x02(\x03\"H\n\x06\x43\x41NIMU\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\x10\n\x08yaw_rate\x18\x07 \x01(\x02\x12\x12\n\ntime_stamp\x18\x32 \x01(\x03\"\xa9\x01\n\x08\x43\x41NFrame\x12 \n\x02ts\x18\x01 \x03(\x0b\x32\x14.CANProto.TurnSignal\x12\x1a\n\x02gt\x18\x02 \x03(\x0b\x32\x0e.CANProto.Gear\x12\x1e\n\x02sp\x18\x03 \x03(\x0b\x32\x12.CANProto.VehSpeed\x12 \n\x02wa\x18\x04 \x03(\x0b\x32\x14.CANProto.WheelAngle\x12\x1d\n\x03imu\x18\x05 \x03(\x0b\x32\x10.CANProto.CANIMU\"\xb1\x01\n\x0b\x43\x41NFrameRaw\x12\x0e\n\x06\x63\x61n_id\x18\x01 \x02(\x05\x12\x0f\n\x07\x63\x61n_dlc\x18\x02 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\x12\x12\n\ntime_stamp\x18\x04 \x02(\x03\x12\x13\n\x08\x63\x61n_type\x18\x05 \x01(\x05:\x01\x30\x12\x16\n\x0b\x63\x61n_channel\x18\x06 \x01(\x05:\x01\x30\"2\n\x08\x43\x41N_TYPE\x12\x15\n\x11\x43\x41N_TYPE_STANDARD\x10\x00\x12\x0f\n\x0b\x43\x41N_TYPE_FD\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CANFRAMERAW_CAN_TYPE = _descriptor.EnumDescriptor(
  name='CAN_TYPE',
  full_name='CANProto.CANFrameRaw.CAN_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAN_TYPE_STANDARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAN_TYPE_FD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=633,
)
_sym_db.RegisterEnumDescriptor(_CANFRAMERAW_CAN_TYPE)


_VEHSPEED = _descriptor.Descriptor(
  name='VehSpeed',
  full_name='CANProto.VehSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='CANProto.VehSpeed.speed', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.VehSpeed.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=68,
)


_WHEELANGLE = _descriptor.Descriptor(
  name='WheelAngle',
  full_name='CANProto.WheelAngle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='CANProto.WheelAngle.angle', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.WheelAngle.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=117,
)


_GEAR = _descriptor.Descriptor(
  name='Gear',
  full_name='CANProto.Gear',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CANProto.Gear.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.Gear.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=159,
)


_TURNSIGNAL = _descriptor.Descriptor(
  name='TurnSignal',
  full_name='CANProto.TurnSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CANProto.TurnSignal.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.TurnSignal.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=207,
)


_CANIMU = _descriptor.Descriptor(
  name='CANIMU',
  full_name='CANProto.CANIMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acc', full_name='CANProto.CANIMU.acc', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='CANProto.CANIMU.yaw', index=1,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate', full_name='CANProto.CANIMU.yaw_rate', index=2,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.CANIMU.time_stamp', index=3,
      number=50, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=281,
)


_CANFRAME = _descriptor.Descriptor(
  name='CANFrame',
  full_name='CANProto.CANFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='CANProto.CANFrame.ts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gt', full_name='CANProto.CANFrame.gt', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sp', full_name='CANProto.CANFrame.sp', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wa', full_name='CANProto.CANFrame.wa', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imu', full_name='CANProto.CANFrame.imu', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=453,
)


_CANFRAMERAW = _descriptor.Descriptor(
  name='CANFrameRaw',
  full_name='CANProto.CANFrameRaw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='can_id', full_name='CANProto.CANFrameRaw.can_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_dlc', full_name='CANProto.CANFrameRaw.can_dlc', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CANProto.CANFrameRaw.data', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='CANProto.CANFrameRaw.time_stamp', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_type', full_name='CANProto.CANFrameRaw.can_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_channel', full_name='CANProto.CANFrameRaw.can_channel', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANFRAMERAW_CAN_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=633,
)

_CANFRAME.fields_by_name['ts'].message_type = _TURNSIGNAL
_CANFRAME.fields_by_name['gt'].message_type = _GEAR
_CANFRAME.fields_by_name['sp'].message_type = _VEHSPEED
_CANFRAME.fields_by_name['wa'].message_type = _WHEELANGLE
_CANFRAME.fields_by_name['imu'].message_type = _CANIMU
_CANFRAMERAW_CAN_TYPE.containing_type = _CANFRAMERAW
DESCRIPTOR.message_types_by_name['VehSpeed'] = _VEHSPEED
DESCRIPTOR.message_types_by_name['WheelAngle'] = _WHEELANGLE
DESCRIPTOR.message_types_by_name['Gear'] = _GEAR
DESCRIPTOR.message_types_by_name['TurnSignal'] = _TURNSIGNAL
DESCRIPTOR.message_types_by_name['CANIMU'] = _CANIMU
DESCRIPTOR.message_types_by_name['CANFrame'] = _CANFRAME
DESCRIPTOR.message_types_by_name['CANFrameRaw'] = _CANFRAMERAW

VehSpeed = _reflection.GeneratedProtocolMessageType('VehSpeed', (_message.Message,), dict(
  DESCRIPTOR = _VEHSPEED,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.VehSpeed)
  ))
_sym_db.RegisterMessage(VehSpeed)

WheelAngle = _reflection.GeneratedProtocolMessageType('WheelAngle', (_message.Message,), dict(
  DESCRIPTOR = _WHEELANGLE,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.WheelAngle)
  ))
_sym_db.RegisterMessage(WheelAngle)

Gear = _reflection.GeneratedProtocolMessageType('Gear', (_message.Message,), dict(
  DESCRIPTOR = _GEAR,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.Gear)
  ))
_sym_db.RegisterMessage(Gear)

TurnSignal = _reflection.GeneratedProtocolMessageType('TurnSignal', (_message.Message,), dict(
  DESCRIPTOR = _TURNSIGNAL,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.TurnSignal)
  ))
_sym_db.RegisterMessage(TurnSignal)

CANIMU = _reflection.GeneratedProtocolMessageType('CANIMU', (_message.Message,), dict(
  DESCRIPTOR = _CANIMU,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.CANIMU)
  ))
_sym_db.RegisterMessage(CANIMU)

CANFrame = _reflection.GeneratedProtocolMessageType('CANFrame', (_message.Message,), dict(
  DESCRIPTOR = _CANFRAME,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.CANFrame)
  ))
_sym_db.RegisterMessage(CANFrame)

CANFrameRaw = _reflection.GeneratedProtocolMessageType('CANFrameRaw', (_message.Message,), dict(
  DESCRIPTOR = _CANFRAMERAW,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CANProto.CANFrameRaw)
  ))
_sym_db.RegisterMessage(CANFrameRaw)


# @@protoc_insertion_point(module_scope)
