# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph.Qt import QtCore, QtGui
import myControls


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)


        #left
        verticalLayout = QtWidgets.QVBoxLayout()
        #left.top
        self.label_cameraContainer = QtWidgets.QLabel()
        self.label_cameraContainer.setObjectName("label")
        verticalLayout.addWidget(self.label_cameraContainer)

        # 左下角小控件
        self.GLView_OrgRadar = myControls.MyGLViewWidget()
        verticalLayout.addWidget(self.GLView_OrgRadar)

        self.button_run_stop = QtWidgets.QPushButton("OnLine")
        verticalLayout.addWidget(self.button_run_stop)
        self.button_mod_select = QtWidgets.QPushButton("Record")
        verticalLayout.addWidget(self.button_mod_select)
        # self.button_log_select = QtWidgets.QPushButton("MyRealLog")
        # verticalLayout.addWidget(self.button_log_select)

        # verticalLayout.setStretch(0,0)


        horizontalLayout = QtWidgets.QHBoxLayout()
        horizontalLayout.addLayout(verticalLayout)

        splitter1 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)


        # 右侧大控件
        self.GLView_FuseRadar = myControls.MyGLViewWidget()

        splitter1.addWidget(self.GLView_FuseRadar)

        self.tableView = QtWidgets.QTableView()
        # 水平方向标签拓展剩下的窗口部分，填满表格
        self.tableView.horizontalHeader().setStretchLastSection(True)
        # 水平方向，表格大小拓展到适当的尺寸
        self.tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableView.verticalHeader().setDefaultSectionSize(5)
        splitter1.addWidget(self.tableView)

        horizontalLayout.addWidget(splitter1)
        self.centralwidget.setLayout(horizontalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("BHAP", "BHAP"))
        self.label_cameraContainer.setText(_translate("MainWindow", "TextLabel"))

