# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import meta_data_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='meta.proto',
  package='Meta',
  serialized_pb=_b('\n\nmeta.proto\x12\x04Meta\x1a\x0fmeta_data.proto\"G\n\x04Meta\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x10\n\x08\x66rame_id\x18\x02 \x02(\x05\x12\x1c\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x0e.MetaData.Data')
  ,
  dependencies=[meta_data_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_META = _descriptor.Descriptor(
  name='Meta',
  full_name='Meta.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Meta.Meta.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='Meta.Meta.frame_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Meta.Meta.data', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=108,
)

_META.fields_by_name['data'].message_type = meta_data_pb2._DATA
DESCRIPTOR.message_types_by_name['Meta'] = _META

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'meta_pb2'
  # @@protoc_insertion_point(class_scope:Meta.Meta)
  ))
_sym_db.RegisterMessage(Meta)


# @@protoc_insertion_point(module_scope)
